//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        public static string CATEGORY_LBL_NAME {
            get {
                return ResourceManager.GetString("CATEGORY_LBL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The field {0} is required.
        /// </summary>
        public static string DATA_ANOTATION_REQUIRED {
            get {
                return ResourceManager.GetString("DATA_ANOTATION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identifier.
        /// </summary>
        public static string ENTITY_LBL_IDENTIFIER {
            get {
                return ResourceManager.GetString("ENTITY_LBL_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred in the request.
        /// </summary>
        public static string EX_MSG_AN_ERROR_OCURRED_REQUEST {
            get {
                return ResourceManager.GetString("EX_MSG_AN_ERROR_OCURRED_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} not found.
        /// </summary>
        public static string EXCEPTION_MSG_NOT_FOUND {
            get {
                return ResourceManager.GetString("EXCEPTION_MSG_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The property {0} cannot be null.
        /// </summary>
        public static string EXCEPTION_MSG_THE_PROPERTY_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("EXCEPTION_MSG_THE_PROPERTY_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Synchronize.
        /// </summary>
        public static string GENERAL_PAGE_BTN_SYNCHRONIZE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_BTN_SYNCHRONIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Academic Level.
        /// </summary>
        public static string GENERAL_PAGE_LBL_ACADEMIC_LEVEL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_ACADEMIC_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Assignment Type.
        /// </summary>
        public static string GENERAL_PAGE_LBL_ASSIGNMENT_TYPE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_ASSIGNMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Class Level.
        /// </summary>
        public static string GENERAL_PAGE_LBL_CLASS_LEVEL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_CLASS_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Course Section.
        /// </summary>
        public static string GENERAL_PAGE_LBL_COURSE_SECTION {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_COURSE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Educational Institution.
        /// </summary>
        public static string GENERAL_PAGE_LBL_EDUCATIONAL_INSTITUTION {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_EDUCATIONAL_INSTITUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failure.
        /// </summary>
        public static string GENERAL_PAGE_LBL_FAILURE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Filter.
        /// </summary>
        public static string GENERAL_PAGE_LBL_FILTER {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a General.
        /// </summary>
        public static string GENERAL_PAGE_LBL_GENERAL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Home.
        /// </summary>
        public static string GENERAL_PAGE_LBL_HOME {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Information.
        /// </summary>
        public static string GENERAL_PAGE_LBL_INFORMATION {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Location.
        /// </summary>
        public static string GENERAL_PAGE_LBL_LOCATION {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Natural Person.
        /// </summary>
        public static string GENERAL_PAGE_LBL_NATURAL_PERSON {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_NATURAL_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Occurrence Type.
        /// </summary>
        public static string GENERAL_PAGE_LBL_OCCUERRENCE_TYPE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_OCCUERRENCE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Portal.
        /// </summary>
        public static string GENERAL_PAGE_LBL_PORTAL {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_PORTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Program Offered.
        /// </summary>
        public static string GENERAL_PAGE_LBL_PROGRAM_OFFERED {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_PROGRAM_OFFERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Responsible.
        /// </summary>
        public static string GENERAL_PAGE_LBL_RESPONSIBLE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_RESPONSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Service List.
        /// </summary>
        public static string GENERAL_PAGE_LBL_SERVICE_LIST {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_SERVICE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rafael.
        /// </summary>
        public static string GENERAL_PAGE_LBL_SEVEN_EDU {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_SEVEN_EDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Student.
        /// </summary>
        public static string GENERAL_PAGE_LBL_STUDENT {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Student resposponsible.
        /// </summary>
        public static string GENERAL_PAGE_LBL_STUDENT_RESPONSIBLE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_STUDENT_RESPONSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Success.
        /// </summary>
        public static string GENERAL_PAGE_LBL_SUCCESS {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Table.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TABLE {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Term Group.
        /// </summary>
        public static string GENERAL_PAGE_LBL_TERM_GROUP {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_TERM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        public static string GENERAL_PAGE_LBL_WARNING {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wellcome.
        /// </summary>
        public static string GENERAL_PAGE_LBL_WELCOME {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_LBL_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successfully Synchronized!.
        /// </summary>
        public static string GENERAL_PAGE_MSG_SUCCESSFULLY_SYNCHRONIZED {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG_SUCCESSFULLY_SYNCHRONIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This field is required!.
        /// </summary>
        public static string GENERAL_PAGE_MSG_THIS_FIELD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("GENERAL_PAGE_MSG_THIS_FIELD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _Rafael - Events.
        /// </summary>
        public static string HANGFIRE_SERVER_NAME {
            get {
                return ResourceManager.GetString("HANGFIRE_SERVER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rafael.
        /// </summary>
        public static string PROJECT_NAME_MVC {
            get {
                return ResourceManager.GetString("PROJECT_NAME_MVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rafael Lima.
        /// </summary>
        public static string SWAGGER_PAGE_LBL_CONTACT {
            get {
                return ResourceManager.GetString("SWAGGER_PAGE_LBL_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a REST API with .NET 6..
        /// </summary>
        public static string SWAGGER_PAGE_LBL_DESCRIPTION {
            get {
                return ResourceManager.GetString("SWAGGER_PAGE_LBL_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rafael - Events.
        /// </summary>
        public static string SWAGGER_PAGE_LBL_TITLE {
            get {
                return ResourceManager.GetString("SWAGGER_PAGE_LBL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This version is obsolete.
        /// </summary>
        public static string SWAGGER_PAGE_LBL_VERSION_OBSOLETE {
            get {
                return ResourceManager.GetString("SWAGGER_PAGE_LBL_VERSION_OBSOLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Synchronization.
        /// </summary>
        public static string SYNCHRONIZATION_PAGE_LBL_HOME {
            get {
                return ResourceManager.GetString("SYNCHRONIZATION_PAGE_LBL_HOME", resourceCulture);
            }
        }
    }
}
